name = "rumble-tournament-bot"
main = "src/worker.js"
compatibility_date = "2025-10-03"

[vars]
# optional; we’ll add secrets in Cloudflare dashboard, not here

[[kv_namespaces]]
binding = "TOURNAMENTS"
id = "<KV_ID_TOURNAMENTS>"   # fill after you create it in dashboard

[[kv_namespaces]]
binding = "USER_WALLETS"
id = "<KV_ID_USER_WALLETS>"
